<?php

return [
    'default_states' => [
        '714A' => 'aislado', '714B' => 'aislado', '715A' => 'aislado', '715B' => 'aislado',
        '809' => 'aislado', '811' => 'aislado', '812' => 'aislado',
        '813' => 'aislado', '814' => 'aislado', '815' => 'aislado', '816' => 'aislado',
        '817' => 'aislado', '818' => 'aislado', '819' => 'aislado',
        '821A' => 'aislado', '821B' => 'aislado',
        '822' => 'aislado', '823' => 'aislado', '824' => 'aislado', '825' => 'aislado',
        '826' => 'aislado', '827' => 'aislado',
        '803' => 'aislado', '808' => 'aislado',
        'UCI-4' => 'no-hay', 'UCI-7' => 'no-hay', 'UCI-8' => 'no-funciona', 'UCI-10' => 'no-hay',
        'UCI-11' => 'no-funciona',
        'UCIN-1' => 'no-funciona', 'UCIN-3' => 'no-funciona', 'UCIN-4' => 'no-funciona', 'UCIN-5' => 'no-funciona',
        'UCIN-7' => 'no-funciona', 'UCIN-8' => 'no-hay', 'UCIN-10' => 'no-hay', 'UCIN-11' => 'no-hay', 'UCIN-12' => 'no-hay',
        'B7-709' => 'no-hay', 'B7-711' => 'no-hay', 'B7-714' => 'aislado', 'B7-715' => 'no-funciona',
        'B7-716' => 'no-funciona', 'B7-717' => 'no-funciona',
        'B8-803' => 'aislado', 'B8-808' => 'aislado', 'B8-809' => 'aislado',
        'B8-811' => 'aislado', 'B8-812' => 'aislado',
        'B8-813' => 'aislado', 'B8-814' => 'aislado', 'B8-815' => 'aislado', 'B8-816' => 'aislado',
        'B8-817' => 'aislado', 'B8-818' => 'aislado', 'B8-819' => 'aislado',
        'B8-820' => 'aislado', 'B8-821A' => 'aislado', 'B8-821B' => 'aislado',
        'B8-822' => 'aislado', 'B8-823' => 'aislado', 'B8-824' => 'aislado',
        'B8-825' => 'aislado', 'B8-826' => 'aislado', 'B8-827' => 'aislado',
        '2-15' => 'no-funciona',
    ],

    'default_observations' => [
        '717A' => 'No funciona el control', '717B' => 'No funciona el control',
        '719A' => 'No funciona el control', '720A' => 'No funciona el control',
        '807B' => 'No tiene base para el control', '808' => 'Cambio de botones',
        '815' => 'No tiene control', '823' => 'No funciona el control',
        'B7-703' => 'Se le safa el llamado',
        '6-RC2' => 'PEGADO EL LLAMADO CON CINTA',
        '6-RT3' => 'PENDIENTE',
        'B6-MR2' => 'LLAMADO SIN CLIPS PARA ASEGURAR A LA BASE',
        'UCI-1' => 'MUESCAS DAÑADAS', 'UCI-2' => 'PULSADOR FLOJO PERO SIRVE',
        'UCI-4' => 'MUESCAS DAÑADAS', 'UCI-5' => 'MUESCAS DAÑADAS', 'UCI-6' => 'MUESCAS DAÑADAS',
        'UCI-8' => 'MUESCAS DAÑADAS', 'UCI-9' => 'MUESCAS DAÑADAS', 'UCI-10' => 'MUESCAS DAÑADAS',
        'UCI-11' => 'NO HAY NO TENEMOS', 'UCI-13' => 'MUESCAS DAÑADAS',
        'UCI-15' => 'MUESCAS DAÑADAS', 'UCI-18' => 'MUESCAS DAÑADAS',
        'UCIN-1' => 'FALTA COMPLETO (NO LO TENEMOS)', 'UCIN-3' => 'FALTA COMPLETO (EN REPARACION)',
        'UCIN-4' => 'FALTA COMPLETO (EN REPARACION)', 'UCIN-5' => 'FALTA COMPLETO (NO LO TENEMOS)',
        'UCIN-7' => 'MUESCAS DEL LLAMADO DAÑADAS', 'UCIN-8' => 'MUESCAS DEL LLAMADO DAÑADAS, LLAMADO ROTO',
        'UCIN-11' => 'PULSADOR', 'UCIN-12' => 'PULSADOR, MUESCAS DAÑADAS',
        'UCIN-13' => 'DAÑADA LAS MUESCAS DEL LLAMADO', 'UCIN-14' => 'PULSADOR DAÑADO',
        '2-15' => 'NO TIENE PILA NI PULSADOR',
        '2-33' => 'PEGADO CON ESPADARAPO, DAÑADA LAS MUESCAS DEL LLAMADO',
        '2-34' => 'PEGADO CON ESPADARAPO, DAÑADA LAS MUESCAS DEL LLAMADO',
        '2-SPA' => 'PENDIENTE', '2-SPB' => 'PENDIENTE',
        '701B' => 'PULSADOR', '705B' => 'PULSADOR', '706A' => 'PULSADOR',
        '708A' => 'PULSADOR', '708B' => 'PULSADOR', '709B' => 'PULSADOR',
        '710B' => 'PULSADOR', '712B' => 'PULSADOR',
        '717A' => 'MUESCAS DAÑADAS', '717B' => 'PULSADOR DAÑADO',
        '718A' => 'PULSADOR DAÑADO', '720A' => 'PULSADOR DAÑADO',
        '721A' => 'PULSADOR', '721B' => 'PULSADOR',
        'B7-703' => 'PENDIENTE', 'B7-709' => 'NO HAY',
        'B7-711' => 'NO HAY', 'B7-715' => 'NO HAY TIMBRE',
        'B7-716' => 'NO HAY TIMBRE', 'B7-717' => 'NO HAY TIMBRE',
        '802' => 'PULSADOR', '805A' => 'PULSADOR', 'B8-805' => 'PULSADOR',
        'B8-808' => 'AISLADO', 'B8-809' => 'AISLADO',
        'B8-812' => 'AISLADO', 'B8-813' => 'AISLADO', 'B8-814' => 'AISLADO',
        'B8-816' => 'AISLADO', 'B8-817' => 'AISLADO',
        'B8-819' => 'AISLADO', 'B8-820' => 'AISLADO',
        'B8-821A' => 'AISLADO', 'B8-821B' => 'AISLADO',
        'B8-822' => 'AISLADO', 'B8-823' => 'AISLADO',
        'B1-ADMH2' => 'MUESCAS DAÑADAS',
    ],
];
